#!perl
use strict;
use warnings;

use AnyPAN::CLI::S3Storage;
AnyPAN::CLI::S3Storage->new_with_argv(@ARGV)->run();

__END__

=pod

=head1 NAME

anypan-merger-s3 - DarkPAN and CPAN mirror merging tool for S3

=head1 SYNOPSIS

anypan-merger-s3 [options] [source_urls ...]

 Options:
   -h|--help                Brief help message
   -v|--verbose             Verbose log
   --aws-access-key-id      AWS Access Key ID (required, default: $AWS_ACCESS_KEY_ID)
   --aws-secret-access-key  AWS Secret Access Key (required, default: $AWS_SECRET_ACCESS_KEY)
   --aws-session-token      AWS Session Token (default: $AWS_SESSION_TOKEN)
   --s3-timeout             S3 Timeout Seconds (defaults: 30s)
   --s3-bucket-name         S3 Bucket Name (required)
   --s3-bucket-region       S3 Bucket Region (required)
   --with-packages          Writes also the packages included in the merged CPAN index
   --source-cache-dir       Source DarkPAN and CPAN mirror cache directory (default: /tmp/AnyPAN)
   --index-cache-timeout    Source DarkPAN and CPAN mirror index cache expiration seconds (default: 300s)
   --request-timeout        HTTP request timeout seconds (default: 30s)
   --max-retries            Max retry count
   --retry-interval         Retry interval
   --retry-jitter-factor    Retry jitter factor

=cut
